### ISSUE TITLE
Signup/Login UI/UX

### ISSUE THREAD

**Issue by rooftopsparrow** [rooftopsparrow/ledger#13]
- [x] Landing Page - Signup form for Name, email, password
- [x] New User - Successful registration message, already signed in. "Welcome to Ledger, here are some things you can do"
- [x] Existing User - Show account details: name, email

**Comment by BProw** [comment]
![sketch_landingpage_1280](https://user-images.githubusercontent.com/23251886/106835867-4e7cff00-6655-11eb-813f-8c701cc3773e.png)

Basic landing page design prototype. Wanted to send to PO/Team to review if it's an acceptable first draft.

**Comment by rooftopsparrow** [comment]
This looks awesome! Definitely like the direction of the logo and that’s a solid base color scheme. Probably want to expand on it and make sure the color pallet works for negative (reddish) values.

**Comment by BProw** [comment]
True. I would like to add elements that display application features as well. I'll try to implement this first draft in Go/React as a potential demo item.

**Comment by BProw** [comment]
I want to apply Go packages (html/template and net/http) to serve html/css files of the first draft on local server without getting into React quite yet. I think this would basically accomplish first sprint goal. I'm hung up on the html/css. If anyone can provide assistance, I'd appreciate it!

**Comment by rooftopsparrow** [comment]
Closed by #25
