### ISSUE TITLE
Prepare Landing Page Demo

### ISSUE THREAD

**Issue by rooftopsparrow** [rooftopsparrow/ledger#23]
- [x] Create prezi
- [x] Ensure clean local demo environment to go through flow

Scope:

1.  Go to landing page without a session
2.  Fill in information
3.  Hit submit
4.  Page then shows successful signup and my account information

Stretch:

5. Show record is in the database
5. Refresh, and I see the account information
6. Delete the session from browser
7. Refresh
8. See the landing page again

Demo Checklist:

- [ ] Show Repository and project management / milestones / projects
- [ ] Show CI - feature file and test
- [ ] Show database initialization and migration
- [ ] Do the Signup UI/UX walkthrough

**Comment by BProw** [comment]
> 1. Go to landing page without a session
> 2. Fill in information
> 3. Hit submit
> 4. Page then shows successful signup and my account information

Added basic functionality to achieve Demo scope goals. Should changes be added to existing pr or create new?

**Comment by rooftopsparrow** [comment]
I'd do a new PR, I've merged the existing branch into master.

**Comment by BProw** [comment]
Finished. Sloppy pr on my end though..change conflicts to landing.go and ledger.html need to be resolved. Pretty simple fix I think but to be safe, probs should have another pair of eyes review #25
