### ISSUE TITLE
Sprint #2 Planning and Decisions

### ISSUE THREAD

**Issue by rooftopsparrow** [rooftopsparrow/ledger#26]
Planning for sprint 2.

- [x] Features wanting to complete
- [x] Github Project with scoped stories to fulfill features
- [x] Add issue to work on demo script

## Features to Complete

1. Finish User Signup Flow ( #17 )
2. Authentication Flow ( #12 )
3. New Account Flow ( #18 )

### Finish user Signup flow:
- Stored in the database
- Session management

### Authentication:
- Preferred stateless ( JWT, APIKeys )
- Login/Logout 
- Maintain Session

### New Account Flow:
1. Promts to fill out information for my bank connection ( this should be heavily influenced by Plaid.com ) 
    1. institution
    2. account number
    3. routing number
    4. security info
2. Connect to account bank
3. View Account Balance

**Comment by BProw** [comment]
@rooftopsparrow Can you send a link to the Plaid.com "Team" you created? Hoping to get familiar to the Sandbox environment with Plaid to complete #18

**Comment by rooftopsparrow** [comment]
I sent you an invite

**Comment by BProw** [comment]
Got it, thanks!

**Comment by rooftopsparrow** [comment]
I’ve started the database implementation and tests for the things needed in Plaid, take a look at #10
